#dictionaries :
#dict_2024_leg_t1_results
#dict_2024_leg_t1_candidats
#dict_2024_leg_t2_results
#dict_2024_leg_t2_candidats
#dict_2019_2024_participation
#dict_2019_2024_results 
#dict_votes # le dict temporaire pour les election europeennes 2019

'''
dict_2024_leg_t1_results = {'Code département': dtype('int64'),
 'Libellé département': dtype('O'),
 'Code commune': dtype('int64'),
 'Libellé commune': dtype('O'),
 'Code BV': dtype('O'),
 'Inscrits': dtype('int64'),
 'Votants': dtype('int64'),
 '% Votants': dtype('O'),
 'Abstentions': dtype('int64'),
 '% Abstentions': dtype('O'),
 'Exprimés': dtype('int64'),
 '% Exprimés/inscrits': dtype('O'),
 '% Exprimés/votants': dtype('O'),
 'Blancs': dtype('int64'),
 '% Blancs/inscrits': dtype('O'),
 '% Blancs/votants': dtype('O'),
 'Nuls': dtype('int64'),
 '% Nuls/inscrits': dtype('O'),
 '% Nuls/votants': dtype('O'),
 'Numéro de panneau 1': dtype('int64'),
 'Nuance candidat 1': dtype('O'),
 'Nom candidat 1': dtype('O'),
 'Prénom candidat 1': dtype('O'),
 'Sexe candidat 1': dtype('O'),
 'Voix 1': dtype('int64'),
 '% Voix/inscrits 1': dtype('O'),
 '% Voix/exprimés 1': dtype('O'),
 'Elu 1': dtype('O'),
 'Numéro de panneau 2': dtype('int64'),
 'Nuance candidat 2': dtype('O'),
 'Nom candidat 2': dtype('O'),
 'Prénom candidat 2': dtype('O'),
 'Sexe candidat 2': dtype('O'),
 'Voix 2': dtype('int64'),
 '% Voix/inscrits 2': dtype('O'),
 '% Voix/exprimés 2': dtype('O'),
 'Elu 2': dtype('O'),
 'Numéro de panneau 3': dtype('int64'),
 'Nuance candidat 3': dtype('O'),
 'Nom candidat 3': dtype('O'),
 'Prénom candidat 3': dtype('O'),
 'Sexe candidat 3': dtype('O'),
 'Voix 3': dtype('int64'),
 '% Voix/inscrits 3': dtype('O'),
 '% Voix/exprimés 3': dtype('O'),
 'Elu 3': dtype('O'),
 'Numéro de panneau 4': dtype('int64'),
 'Nuance candidat 4': dtype('O'),
 'Nom candidat 4': dtype('O'),
 'Prénom candidat 4': dtype('O'),
 'Sexe candidat 4': dtype('O'),
 'Voix 4': dtype('int64'),
 '% Voix/inscrits 4': dtype('O'),
 '% Voix/exprimés 4': dtype('O'),
 'Elu 4': dtype('O'),
 'Numéro de panneau 5': dtype('float64'),
 'Nuance candidat 5': dtype('O'),
 'Nom candidat 5': dtype('O'),
 'Prénom candidat 5': dtype('O'),
 'Sexe candidat 5': dtype('O'),
 'Voix 5': dtype('float64'),
 '% Voix/inscrits 5': dtype('O'),
 '% Voix/exprimés 5': dtype('O'),
 'Elu 5': dtype('O'),
 'Numéro de panneau 6': dtype('float64'),
 'Nuance candidat 6': dtype('O'),
 'Nom candidat 6': dtype('O'),
 'Prénom candidat 6': dtype('O'),
 'Sexe candidat 6': dtype('O'),
 'Voix 6': dtype('float64'),
 '% Voix/inscrits 6': dtype('O'),
 '% Voix/exprimés 6': dtype('O'),
 'Elu 6': dtype('O'),
 'Numéro de panneau 7': dtype('float64'),
 'Nuance candidat 7': dtype('O'),
 'Nom candidat 7': dtype('O'),
 'Prénom candidat 7': dtype('O'),
 'Sexe candidat 7': dtype('O'),
 'Voix 7': dtype('float64'),
 '% Voix/inscrits 7': dtype('O'),
 '% Voix/exprimés 7': dtype('O'),
 'Elu 7': dtype('O'),
 'Numéro de panneau 8': dtype('float64'),
 'Nuance candidat 8': dtype('O'),
 'Nom candidat 8': dtype('O'),
 'Prénom candidat 8': dtype('O'),
 'Sexe candidat 8': dtype('O'),
 'Voix 8': dtype('float64'),
 '% Voix/inscrits 8': dtype('O'),
 '% Voix/exprimés 8': dtype('O'),
 'Elu 8': dtype('O'),
 'Numéro de panneau 9': dtype('float64'),
 'Nuance candidat 9': dtype('O'),
 'Nom candidat 9': dtype('O'),
 'Prénom candidat 9': dtype('O'),
 'Sexe candidat 9': dtype('O'),
 'Voix 9': dtype('float64'),
 '% Voix/inscrits 9': dtype('O'),
 '% Voix/exprimés 9': dtype('O'),
 'Elu 9': dtype('float64'),
 'Numéro de panneau 10': dtype('float64'),
 'Nuance candidat 10': dtype('O'),
 'Nom candidat 10': dtype('O'),
 'Prénom candidat 10': dtype('O'),
 'Sexe candidat 10': dtype('O'),
 'Voix 10': dtype('float64'),
 '% Voix/inscrits 10': dtype('O'),
 '% Voix/exprimés 10': dtype('O'),
 'Elu 10': dtype('O'),
 'Numéro de panneau 11': dtype('float64'),
 'Nuance candidat 11': dtype('O'),
 'Nom candidat 11': dtype('O'),
 'Prénom candidat 11': dtype('O'),
 'Sexe candidat 11': dtype('O'),
 'Voix 11': dtype('float64'),
 '% Voix/inscrits 11': dtype('O'),
 '% Voix/exprimés 11': dtype('O'),
 'Elu 11': dtype('O'),
 'Numéro de panneau 12': dtype('float64'),
 'Nuance candidat 12': dtype('O'),
 'Nom candidat 12': dtype('O'),
 'Prénom candidat 12': dtype('O'),
 'Sexe candidat 12': dtype('O'),
 'Voix 12': dtype('float64'),
 '% Voix/inscrits 12': dtype('O'),
 '% Voix/exprimés 12': dtype('O'),
 'Elu 12': dtype('float64'),
 'Numéro de panneau 13': dtype('float64'),
 'Nuance candidat 13': dtype('O'),
 'Nom candidat 13': dtype('O'),
 'Prénom candidat 13': dtype('O'),
 'Sexe candidat 13': dtype('O'),
 'Voix 13': dtype('float64'),
 '% Voix/inscrits 13': dtype('O'),
 '% Voix/exprimés 13': dtype('O'),
 'Elu 13': dtype('float64'),
 'Numéro de panneau 14': dtype('float64'),
 'Nuance candidat 14': dtype('O'),
 'Nom candidat 14': dtype('O'),
 'Prénom candidat 14': dtype('O'),
 'Sexe candidat 14': dtype('O'),
 'Voix 14': dtype('float64'),
 '% Voix/inscrits 14': dtype('O'),
 '% Voix/exprimés 14': dtype('O'),
 'Elu 14': dtype('float64'),
 'Numéro de panneau 15': dtype('float64'),
 'Nuance candidat 15': dtype('O'),
 'Nom candidat 15': dtype('O'),
 'Prénom candidat 15': dtype('O'),
 'Sexe candidat 15': dtype('O'),
 'Voix 15': dtype('float64'),
 '% Voix/inscrits 15': dtype('O'),
 '% Voix/exprimés 15': dtype('O'),
 'Elu 15': dtype('float64'),
 'Numéro de panneau 16': dtype('float64'),
 'Nuance candidat 16': dtype('O'),
 'Nom candidat 16': dtype('O'),
 'Prénom candidat 16': dtype('O'),
 'Sexe candidat 16': dtype('O'),
 'Voix 16': dtype('float64'),
 '% Voix/inscrits 16': dtype('O'),
 '% Voix/exprimés 16': dtype('O'),
 'Elu 16': dtype('float64'),
 'Numéro de panneau 17': dtype('float64'),
 'Nuance candidat 17': dtype('O'),
 'Nom candidat 17': dtype('O'),
 'Prénom candidat 17': dtype('O'),
 'Sexe candidat 17': dtype('O'),
 'Voix 17': dtype('float64'),
 '% Voix/inscrits 17': dtype('O'),
 '% Voix/exprimés 17': dtype('O'),
 'Elu 17': dtype('float64'),
 'Numéro de panneau 18': dtype('float64'),
 'Nuance candidat 18': dtype('O'),
 'Nom candidat 18': dtype('O'),
 'Prénom candidat 18': dtype('O'),
 'Sexe candidat 18': dtype('O'),
 'Voix 18': dtype('float64'),
 '% Voix/inscrits 18': dtype('O'),
 '% Voix/exprimés 18': dtype('O'),
 'Elu 18': dtype('float64'),
 'Numéro de panneau 19': dtype('float64'),
 'Nuance candidat 19': dtype('O'),
 'Nom candidat 19': dtype('O'),
 'Prénom candidat 19': dtype('O'),
 'Sexe candidat 19': dtype('O'),
 'Voix 19': dtype('float64'),
 '% Voix/inscrits 19': dtype('O'),
 '% Voix/exprimés 19': dtype('O'),
 'Elu 19': dtype('float64')}

dict_2024_leg_t1_candidats = {'Code département': dtype('O'),
 'Département': dtype('O'),
 'Code circonscription': dtype('O'),
 'Libellé circonscription': dtype('O'),
 'Numéro de panneau': dtype('int64'),
 'N° dépôt': dtype('int64'),
 'Sexe du candidat': dtype('O'),
 'Nom du candidat': dtype('O'),
 'Prénom du candidat': dtype('O'),
 'Date de naissance du candidat': dtype('O'),
 'Code nuance': dtype('O'),
 'Profession': dtype('O'),
 'Sortant': dtype('O'),
 'Sexe remplaçant': dtype('O'),
 'Nom remplaçant': dtype('O'),
 'Prénom remplaçant': dtype('O'),
 'Date de naissance remplaçant': dtype('O'),
 'Sortant remplaçant': dtype('O')}

dict_2024_leg_t2_results = {'Code département': dtype('int64'),
 'Libellé département': dtype('O'),
 'Code commune': dtype('int64'),
 'Libellé commune': dtype('O'),
 'Code BV': dtype('O'),
 'Inscrits': dtype('int64'),
 'Votants': dtype('int64'),
 '% Votants': dtype('O'),
 'Abstentions': dtype('int64'),
 '% Abstentions': dtype('O'),
 'Exprimés': dtype('int64'),
 '% Exprimés/inscrits': dtype('O'),
 '% Exprimés/votants': dtype('O'),
 'Blancs': dtype('int64'),
 '% Blancs/inscrits': dtype('O'),
 '% Blancs/votants': dtype('O'),
 'Nuls': dtype('int64'),
 '% Nuls/inscrits': dtype('O'),
 '% Nuls/votants': dtype('O'),
 'Numéro de panneau 1': dtype('int64'),
 'Nuance candidat 1': dtype('O'),
 'Nom candidat 1': dtype('O'),
 'Prénom candidat 1': dtype('O'),
 'Sexe candidat 1': dtype('O'),
 'Voix 1': dtype('int64'),
 '% Voix/inscrits 1': dtype('O'),
 '% Voix/exprimés 1': dtype('O'),
 'Elu 1': dtype('O'),
 'Numéro de panneau 2': dtype('float64'),
 'Nuance candidat 2': dtype('O'),
 'Nom candidat 2': dtype('O'),
 'Prénom candidat 2': dtype('O'),
 'Sexe candidat 2': dtype('O'),
 'Voix 2': dtype('float64'),
 '% Voix/inscrits 2': dtype('O'),
 '% Voix/exprimés 2': dtype('O'),
 'Elu 2': dtype('O'),
 'Numéro de panneau 3': dtype('float64'),
 'Nuance candidat 3': dtype('O'),
 'Nom candidat 3': dtype('O'),
 'Prénom candidat 3': dtype('O'),
 'Sexe candidat 3': dtype('O'),
 'Voix 3': dtype('float64'),
 '% Voix/inscrits 3': dtype('O'),
 '% Voix/exprimés 3': dtype('O'),
 'Elu 3': dtype('O'),
 'Numéro de panneau 4': dtype('float64'),
 'Nuance candidat 4': dtype('O'),
 'Nom candidat 4': dtype('O'),
 'Prénom candidat 4': dtype('O'),
 'Sexe candidat 4': dtype('O'),
 'Voix 4': dtype('float64'),
 '% Voix/inscrits 4': dtype('O'),
 '% Voix/exprimés 4': dtype('O'),
 'Elu 4': dtype('float64')}

dict_2024_leg_t2_candidats = {'Code département': dtype('O'),
 'Département': dtype('O'),
 'Code circonscription': dtype('O'),
 'Libellé circonscription': dtype('O'),
 'Numéro de panneau': dtype('int64'),
 'N° dépôt': dtype('int64'),
 'Sexe du candidat': dtype('O'),
 'Nom du candidat': dtype('O'),
 'Prénom du candidat': dtype('O'),
 'Date de naissance du candidat': dtype('O'),
 'Code nuance': dtype('O'),
 'Profession': dtype('O'),
 'Sortant': dtype('O'),
 'Sexe remplaçant': dtype('O'),
 'Nom remplaçant': dtype('O'),
 'Prénom remplaçant': dtype('O'),
 'Date de naissance remplaçant': dtype('O'),
 'Sortant remplaçant': dtype('O')}

dict_2019_2024_participation = {'id_election': dtype('O'),
 'id_brut_miom': dtype('O'),
 'Code du département': dtype('O'),
 'Libellé du département': dtype('O'),
 'Code de la commune': dtype('O'),
 'Libellé de la commune': dtype('O'),
 'Code du b.vote': dtype('O'),
 'Inscrits': dtype('int32'),
 'Abstentions': dtype('int32'),
 '% Abs/Ins': dtype('float32'),
 'Votants': dtype('int32'),
 '% Vot/Ins': dtype('float32'),
 'Blancs': dtype('float64'),
 '% Blancs/Ins': dtype('float32'),
 '% Blancs/Vot': dtype('float32'),
 'Nuls': dtype('int32'),
 '% Nuls/Ins': dtype('float32'),
 '% Nuls/Vot': dtype('float32'),
 'Exprimés': dtype('int32'),
 '% Exp/Ins': dtype('float32'),
 '% Exp/Vot': dtype('float32'),
 'Code de la circonscription': dtype('O'),
 'Libellé de la circonscription': dtype('O'),
 'Code du canton': dtype('O'),
 'Libellé du canton': dtype('O')}

dict_2019_2024_results = {'id_election': dtype('O'),
 'id_brut_miom': dtype('O'),
 'Code du département': dtype('O'),
 'Code de la commune': dtype('O'),
 'Code du b.vote': dtype('O'),
 'N°Panneau': dtype('float64'),
 'Libellé Abrégé Liste': dtype('O'),
 'Libellé Etendu Liste': dtype('O'),
 'Nom Tête de Liste': dtype('O'),
 'Voix': dtype('float64'),
 '% Voix/Ins': dtype('float32'),
 '% Voix/Exp': dtype('float32'),
 'Sexe': dtype('O'),
 'Nom': dtype('O'),
 'Prénom': dtype('O'),
 'Nuance': dtype('O'),
 'Binôme': dtype('O'),
 'Liste': dtype('O')}


'''

dict_listes_2019 = {
    'Libellé de la commune' : 'first',
    'Inscrits' : 'first',
    'Abstentions': 'first', 
    'Nuls' : 'first' , 
    'Abstentions' : 'first',
    'Exprimés': 'first', 
    'Voix' : 'sum',
    }